version: '3.9'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3308:3306" # Map host port 3308 to container port 3306 for accessibility 3309 for server, 3308 for dev
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "face_cake_db"
      MYSQL_USER: "divt"
      MYSQL_PASSWORD: "divt"
    volumes:
      - ./data/mysql:/var/lib/mysql # Consider mapping data volume for persistence

  nestjs-app:
    build: .
    ports:
      - "8443:8443" # 8443:8443 for server, 8080:8080 for dev
    restart: always
    environment:
      - DATABASE=face_cake_db
      - DATABASE_TYPE=mysql
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - MEDIA_UPLOAD_PATH=public/image
      - API_HOST=http://127.0.0.1:8080 # http://127.0.0.1:8080 for dev, 
    depends_on:
      - mysql # Ensure MySQL is running before starting the NestJS app
    volumes:
      - ./data/public:/user/src/be-app/public # Mount the volume to the desired directory

networks:
  my-network:
    # Create a network for service communication
    external: true # Avoid container collisions between your system and Docker

volumes:
  mysql-data: # Optional persistent volume for MySQL data
